### ISSUE TITLE
已经有新版本5.4.3了，是否更新一下？

### ISSUE THREAD

**Issue by lovefox666** [RonxBulld/HPSocket4Python#1]
已经有新版本5.4.3了，是否更新一下？

**Comment by lovefox666** [comment]
能否留个联系方式QQ，想请教一下。
我有一个需求，由于设备需要内外网物理隔离，内网要发送数据到外网，通过一个串口设备，串口设备可用手机的4G网络通过TCP转发数据到外网服务器。请问：
服务器端可以用这个框架不？

**Comment by RonxBulld** [comment]
> 已经有新版本5.4.3了，是否更新一下？

如果不需要使用新的API接口的话只需要更新DLL即可。

**Comment by RonxBulld** [comment]
> 能否留个联系方式QQ，想请教一下。
> 我有一个需求，由于设备需要内外网物理隔离，内网要发送数据到外网，通过一个串口设备，串口设备可用手机的4G网络通过TCP转发数据到外网服务器。请问：
> 服务器端可以用这个框架不？

这个请在HP的群里寻求技术支持。
